// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGnxhLPTZA7lUggfVA7RNvYqhRnKGkDho',
    appId: '1:14651319731:web:941ce7e2cf14d1b40cd7c6',
    messagingSenderId: '14651319731',
    projectId: 'todo-list-68760',
    authDomain: 'todo-list-68760.firebaseapp.com',
    storageBucket: 'todo-list-68760.appspot.com',
    measurementId: 'G-EBB5FK9L2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDozEmPkWpRsz9-TwdqpkSfFHOMkpRCIno',
    appId: '1:14651319731:android:f0e99270176ddc430cd7c6',
    messagingSenderId: '14651319731',
    projectId: 'todo-list-68760',
    storageBucket: 'todo-list-68760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvLepn2n-210GqxXF_DjC3FJ_fNea2hEQ',
    appId: '1:14651319731:ios:d7197d9b31402e6f0cd7c6',
    messagingSenderId: '14651319731',
    projectId: 'todo-list-68760',
    storageBucket: 'todo-list-68760.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvLepn2n-210GqxXF_DjC3FJ_fNea2hEQ',
    appId: '1:14651319731:ios:47c8bfca1de61c450cd7c6',
    messagingSenderId: '14651319731',
    projectId: 'todo-list-68760',
    storageBucket: 'todo-list-68760.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
